### ISSUE TITLE
Figures not displayed

### ISSUE THREAD

**Issue by DeAngelisA** [UniLuFS2020-ReplicationSeminar/Replication-Paper-Ato-Dan-#7]
@ato-h-96 and @DanSchlaeger : I think the problem is in [this line](https://github.com/UniLuFS2020-ReplicationSeminar/Replication-Paper-Ato-Dan-/blob/d911465bf20ff7c02c482e4dc85e5f9089e6a580/Report/Replication_Report.Rmd#L11). It sets globally the option `include = FALSE` which is excluding all the chunks from appearing in the document! Try deleting this.
A.

**Comment by DanSchlaeger** [comment]
thanks, this solved our problem!
